export enum DataType {
  STRING = 'STRING',
  NUMERIC = 'NUMERIC',
  BOOLEAN = 'BOOLEAN',
  LOCATION = 'LOCATION',
  HEXADECIMAL = 'HEXADECIMAL',
  ENUM = 'ENUM',
  VECTOR = 'VECTOR',
  DATE = 'DATE',
  DURATION = 'DURATION',
  // REFERENCE = 'REFERENCE',
  COLOR = 'COLOR',
  LINK = 'LINK'
}
